Country.create!([
                  { brname: 'Afeganistão', name: 'Afghanistan',
                    a2: 'AF', a3: 'AFG', number: 4 },
                  { brname: 'Albânia', name: 'Albania',
                    a2: 'AL', a3: 'ALB', number: 8 },
                  { brname: 'Alemanha', name: 'Germany',
                    a2: 'DE', a3: 'DEU', number: 276 },
                  { brname: 'Andorra', name: 'Andorra',
                    a2: 'AD', a3: 'AND', number: 20 },
                  { brname: 'Angola', name: 'Angola',
                    a2: 'AO', a3: 'AGO', number: 24 },
                  { brname: 'Anguilla', name: 'Anguilla',
                    a2: 'AI', a3: 'AIA', number: 660 },
                  { brname: 'Antilhas Holandesas', name: 'Netherlands Antilles',
                    a2: 'AN', a3: 'ANT', number: 530 },
                  { brname: 'Antártida', name: 'Antarctica',
                    a2: 'AQ', a3: 'ATA', number: 10 },
                  { brname: 'Antígua e Barbuda', name: 'Antigua and Barbuda',
                    a2: 'AG', a3: 'ATG', number: 28 },
                  { brname: 'Argentina', name: 'Argentina',
                    a2: 'AR', a3: 'ARG', number: 32 },
                  { brname: 'Argélia', name: 'Algeria',
                    a2: 'DZ', a3: 'DZA', number: 12 },
                  { brname: 'Arménia', name: 'Armenia',
                    a2: 'AM', a3: 'ARM', number: 51 },
                  { brname: 'Aruba', name: 'Aruba',
                    a2: 'AW', a3: 'ABW', number: 533 },
                  { brname: 'Arábia Saudita', name: 'Saudi Arabia',
                    a2: 'SA', a3: 'SAU', number: 682 },
                  { brname: 'Austrália', name: 'Australia',
                    a2: 'AU', a3: 'AUS', number: 36 },
                  { brname: 'Azerbaijão', name: 'Azerbaijan',
                    a2: 'AZ', a3: 'AZE', number: 31 },
                  { brname: 'Bahamas', name: 'Bahamas',
                    a2: 'BS', a3: 'BHS', number: 44 },
                  { brname: 'Bahrein', name: 'Bahrain',
                    a2: 'BH', a3: 'BHR', number: 48 },
                  { brname: 'Bangladesh', name: 'Bangladesh',
                    a2: 'BD', a3: 'BGD', number: 50 },
                  { brname: 'Barbados', name: 'Barbados',
                    a2: 'BB', a3: 'BRB', number: 52 },
                  { brname: 'Belize', name: 'Belize',
                    a2: 'BZ', a3: 'BLZ', number: 84 },
                  { brname: 'Benim', name: 'Benin',
                    a2: 'BJ', a3: 'BEN', number: 204 },
                  { brname: 'Bermudas', name: 'Bermuda',
                    a2: 'BM', a3: 'BMU', number: 60 },
                  { brname: 'Bielorrússia', name: 'Belarus',
                    a2: 'BY', a3: 'BLR', number: 112 },
                  { brname: 'Bolívia', name: 'Bolivia',
                    a2: 'BO', a3: 'BOL', number: 68 },
                  { brname: 'Botswana', name: 'Botswana',
                    a2: 'BW', a3: 'BWA', number: 72 },
                  { brname: 'Brasil', name: 'Brazil',
                    a2: 'BR', a3: 'BRA', number: 76 },
                  { brname: 'Brunei', name: 'Brunei Darussalam',
                    a2: 'BN', a3: 'BRN', number: 96 },
                  { brname: 'Bulgária', name: 'Bulgaria',
                    a2: 'BG', a3: 'BGR', number: 100 },
                  { brname: 'Burkina Faso', name: 'Burkina Faso',
                    a2: 'BF', a3: 'BFA', number: 854 },
                  { brname: 'Burundi', name: 'Burundi',
                    a2: 'BI', a3: 'BDI', number: 108 },
                  { brname: 'Butão', name: 'Bhutan',
                    a2: 'BT', a3: 'BTN', number: 64 },
                  { brname: 'Bélgica', name: 'Belgium',
                    a2: 'BE', a3: 'BEL', number: 56 },
                  { brname: 'Bósnia e Herzegovina', name: 'Bosnia and Herzegowina',
                    a2: 'BA', a3: 'BIH', number: 70 },
                  { brname: 'Cabo Verde', name: 'Cape Verde',
                    a2: 'CV', a3: 'CPV', number: 132 },
                  { brname: 'Camarões', name: 'Cameroon',
                    a2: 'CM', a3: 'CMR', number: 120 },
                  { brname: 'Camboja', name: 'Cambodia',
                    a2: 'KH', a3: 'KHM', number: 116 },
                  { brname: 'Canadá', name: 'Canada',
                    a2: 'CA', a3: 'CAN', number: 124 },
                  { brname: 'Catar', name: 'Qatar',
                    a2: 'QA', a3: 'QAT', number: 634 },
                  { brname: 'Cazaquistão', name: 'Kazakhstan',
                    a2: 'KZ', a3: 'KAZ', number: 398 },
                  { brname: 'Chade', name: 'Chad',
                    a2: 'TD', a3: 'TCD', number: 148 },
                  { brname: 'Chile', name: 'Chile',
                    a2: 'CL', a3: 'CHL', number: 152 },
                  { brname: 'China', name: 'China',
                    a2: 'CN', a3: 'CHN', number: 156 },
                  { brname: 'Chipre', name: 'Cyprus',
                    a2: 'CY', a3: 'CYP', number: 196 },
                  { brname: 'Colômbia', name: 'Colombia',
                    a2: 'CO', a3: 'COL', number: 170 },
                  { brname: 'Comores', name: 'Comoros',
                    a2: 'KM', a3: 'COM', number: 174 },
                  { brname: 'Coreia do Sul', name: 'Korea - Republic of',
                    a2: 'KR', a3: 'KOR', number: 410 },
                  { brname: 'Costa Rica', name: 'Costa Rica',
                    a2: 'CR', a3: 'CRI', number: 188 },
                  { brname: 'Costa do Marfim', name: "Cote D'ivoire",
                    a2: 'CI', a3: 'CIV', number: 384 },
                  { brname: 'Croácia', name: 'Croatia (local Name: Hrvatska)',
                    a2: 'HR', a3: 'HRV', number: 191 },
                  { brname: 'Cuba', name: 'Cuba',
                    a2: 'CU', a3: 'CUB', number: 192 },
                  { brname: 'Dinamarca', name: 'Denmark',
                    a2: 'DK', a3: 'DNK', number: 208 },
                  { brname: 'Djibouti', name: 'Djibouti',
                    a2: 'DJ', a3: 'DJI', number: 262 },
                  { brname: 'Dominica', name: 'Dominica',
                    a2: 'DM', a3: 'DMA', number: 212 },
                  { brname: 'Egito', name: 'Egypt',
                    a2: 'EG', a3: 'EGY', number: 818 },
                  { brname: 'El Salvador', name: 'El Salvador',
                    a2: 'SV', a3: 'SLV', number: 222 },
                  { brname: 'Emirados Árabes Unidos', name: 'United Arab Emirates',
                    a2: 'AE', a3: 'ARE', number: 784 },
                  { brname: 'Equador', name: 'Ecuador',
                    a2: 'EC', a3: 'ECU', number: 218 },
                  { brname: 'Eritreia', name: 'Eritrea',
                    a2: 'ER', a3: 'ERI', number: 232 },
                  { brname: 'Eslováquia', name: 'Slovakia',
                    a2: 'SK', a3: 'SVK', number: 703 },
                  { brname: 'Eslovênia', name: 'Slovenia',
                    a2: 'SI', a3: 'SVN', number: 705 },
                  { brname: 'Espanha', name: 'Spain',
                    a2: 'ES', a3: 'ESP', number: 724 },
                  { brname: 'Estados Federados da Micronésia', name: 'Micronesia - Federated States of',
                    a2: 'FM', a3: 'FSM', number: 583 },
                  { brname: 'Estados Unidos', name: 'United States',
                    a2: 'US', a3: 'USA', number: 840 },
                  { brname: 'Estónia', name: 'Estonia',
                    a2: 'EE', a3: 'EST', number: 233 },
                  { brname: 'Etiópia', name: 'Ethiopia',
                    a2: 'ET', a3: 'ETH', number: 231 },
                  { brname: 'Fiji', name: 'Fiji',
                    a2: 'FJ', a3: 'FJI', number: 242 },
                  { brname: 'Filipinas', name: 'Philippines',
                    a2: 'PH', a3: 'PHL', number: 608 },
                  { brname: 'Finlândia', name: 'Finland',
                    a2: 'FI', a3: 'FIN', number: 246 },
                  { brname: 'França', name: 'France',
                    a2: 'FR', a3: 'FRA', number: 250 },
                  { brname: 'Gabão', name: 'Gabon',
                    a2: 'GA', a3: 'GAB', number: 266 },
                  { brname: 'Gana', name: 'Ghana',
                    a2: 'GH', a3: 'GHA', number: 288 },
                  { brname: 'Geórgia', name: 'Georgia',
                    a2: 'GE', a3: 'GEO', number: 268 },
                  { brname: 'Gibraltar', name: 'Gibraltar',
                    a2: 'GI', a3: 'GIB', number: 292 },
                  { brname: 'Granada', name: 'Grenada',
                    a2: 'GD', a3: 'GRD', number: 308 },
                  { brname: 'Gronelândia', name: 'Greenland',
                    a2: 'GL', a3: 'GRL', number: 304 },
                  { brname: 'Grécia', name: 'Greece',
                    a2: 'GR', a3: 'GRC', number: 300 },
                  { brname: 'Guadalupe', name: 'Guadeloupe',
                    a2: 'GP', a3: 'GLP', number: 312 },
                  { brname: 'Guam', name: 'Guam',
                    a2: 'GU', a3: 'GUM', number: 316 },
                  { brname: 'Guatemala', name: 'Guatemala',
                    a2: 'GT', a3: 'GTM', number: 320 },
                  { brname: 'Guiana', name: 'Guyana',
                    a2: 'GY', a3: 'GUY', number: 328 },
                  { brname: 'Guiana Francesa', name: 'French Guiana',
                    a2: 'GF', a3: 'GUF', number: 254 },
                  { brname: 'Guiné', name: 'Guinea',
                    a2: 'GN', a3: 'GIN', number: 324 },
                  { brname: 'Guiné Equatorial', name: 'Equatorial Guinea',
                    a2: 'GQ', a3: 'GNQ', number: 226 },
                  { brname: 'Guiné-Bissau', name: 'Guinea-Bissau',
                    a2: 'GW', a3: 'GNB', number: 624 },
                  { brname: 'Gâmbia', name: 'Gambia',
                    a2: 'GM', a3: 'GMB', number: 270 },
                  { brname: 'Haiti', name: 'Haiti',
                    a2: 'HT', a3: 'HTI', number: 332 },
                  { brname: 'Honduras', name: 'Honduras',
                    a2: 'HN', a3: 'HND', number: 340 },
                  { brname: 'Hong Kong', name: 'Hong Kong',
                    a2: 'HK', a3: 'HKG', number: 344 },
                  { brname: 'Hungria', name: 'Hungary',
                    a2: 'HU', a3: 'HUN', number: 348 },
                  { brname: 'Ilha Bouvet', name: 'Bouvet Island',
                    a2: 'BV', a3: 'BVT', number: 74 },
                  { brname: 'Ilha Heard e Ilhas McDonald', name: 'Heard and Mc Donald Islands',
                    a2: 'HM', a3: 'HMD', number: 334 },
                  { brname: 'Ilha Norfolk', name: 'Norfolk Island',
                    a2: 'NF', a3: 'NFK', number: 574 },
                  { brname: 'Ilha do Natal', name: 'Christmas Island',
                    a2: 'CX', a3: 'CXR', number: 162 },
                  { brname: 'Ilhas Cayman', name: 'Cayman Islands',
                    a2: 'KY', a3: 'CYM', number: 136 },
                  { brname: 'Ilhas Cocos (Keeling)', name: 'Cocos (KEELING) Islands',
                    a2: 'CC', a3: 'CCK', number: 166 },
                  { brname: 'Ilhas Cook', name: 'Cook Islands',
                    a2: 'CK', a3: 'COK', number: 184 },
                  { brname: 'Ilhas Feroé', name: 'Faroe Islands',
                    a2: 'FO', a3: 'FRO', number: 234 },
                  { brname: 'Ilhas Geórgia do Sul e Sandwich do Sul', name: 'South Georgia and The South Sandwich Islands',
                    a2: 'GS', a3: 'SGS', number: 239 },
                  { brname: 'Ilhas Malvinas', name: 'Falkland Islands (MALVINAS)',
                    a2: 'FK', a3: 'FLK', number: 238 },
                  { brname: 'Ilhas Marshall', name: 'Marshall Islands',
                    a2: 'MH', a3: 'MHL', number: 584 },
                  { brname: 'Ilhas Menores Distantes dos Estados Unidos', name: 'United States Minor Outlying Islands',
                    a2: 'UM', a3: 'UMI', number: 581 },
                  { brname: 'Ilhas Salomão', name: 'Solomon Islands',
                    a2: 'SB', a3: 'SLB', number: 90 },
                  { brname: 'Ilhas Virgens Americanas', name: 'Virgin Islands (U.S.)',
                    a2: 'VI', a3: 'VIR', number: 850 },
                  { brname: 'Ilhas Virgens Britânicas', name: 'Virgin Islands (British)',
                    a2: 'VG', a3: 'VGB', number: 92 },
                  { brname: 'Ilhas Åland', name: 'Aaland Islands',
                    a2: 'AX', a3: 'ALA', number: 248 },
                  { brname: 'Indonésia', name: 'Indonesia',
                    a2: 'ID', a3: 'IDN', number: 360 },
                  { brname: 'Iraque', name: 'Iraq',
                    a2: 'IQ', a3: 'IRQ', number: 368 },
                  { brname: 'Irlanda', name: 'Ireland',
                    a2: 'IE', a3: 'IRL', number: 372 },
                  { brname: 'Irão', name: 'Iran (Islamic Republic of)',
                    a2: 'IR', a3: 'IRN', number: 364 },
                  { brname: 'Islândia', name: 'Iceland',
                    a2: 'IS', a3: 'ISL', number: 352 },
                  { brname: 'Israel', name: 'Israel',
                    a2: 'IL', a3: 'ISR', number: 376 },
                  { brname: 'Itália', name: 'Italy',
                    a2: 'IT', a3: 'ITA', number: 380 },
                  { brname: 'Iémen/Iêmen', name: 'Yemen',
                    a2: 'YE', a3: 'YEM', number: 887 },
                  { brname: 'Jamaica', name: 'Jamaica',
                    a2: 'JM', a3: 'JAM', number: 388 },
                  { brname: 'Japão', name: 'Japan',
                    a2: 'JP', a3: 'JPN', number: 392 },
                  { brname: 'Jordânia', name: 'Jordan',
                    a2: 'JO', a3: 'JOR', number: 400 },
                  { brname: 'Kiribati', name: 'Kiribati',
                    a2: 'KI', a3: 'KIR', number: 296 },
                  { brname: 'Kuwait', name: 'Kuwait',
                    a2: 'KW', a3: 'KWT', number: 414 },
                  { brname: 'Laos', name: "Lao People's Democratic Republic",
                    a2: 'LA', a3: 'LAO', number: 418 },
                  { brname: 'Lesoto', name: 'Lesotho',
                    a2: 'LS', a3: 'LSO', number: 426 },
                  { brname: 'Letônia', name: 'Latvia',
                    a2: 'LV', a3: 'LVA', number: 428 },
                  { brname: 'Libéria', name: 'Liberia',
                    a2: 'LR', a3: 'LBR', number: 430 },
                  { brname: 'Liechtenstein', name: 'Liechtenstein',
                    a2: 'LI', a3: 'LIE', number: 438 },
                  { brname: 'Lituânia', name: 'Lithuania',
                    a2: 'LT', a3: 'LTU', number: 440 },
                  { brname: 'Luxemburgo', name: 'Luxembourg',
                    a2: 'LU', a3: 'LUX', number: 442 },
                  { brname: 'Líbano', name: 'Lebanon',
                    a2: 'LB', a3: 'LBN', number: 422 },
                  { brname: 'Líbia', name: 'Libyan Arab Jamahiriya',
                    a2: 'LY', a3: 'LBY', number: 434 },
                  { brname: 'Macau', name: 'Macau',
                    a2: 'MO', a3: 'MAC', number: 446 },
                  { brname: 'Macedónia', name: 'Macedonia - The Former Yugoslav Republic of',
                    a2: 'MK', a3: 'MKD', number: 807 },
                  { brname: 'Madagáscar', name: 'Madagascar',
                    a2: 'MG', a3: 'MDG', number: 450 },
                  { brname: 'Malawi', name: 'Malawi',
                    a2: 'MW', a3: 'MWI', number: 454 },
                  { brname: 'Maldivas', name: 'Maldives',
                    a2: 'MV', a3: 'MDV', number: 462 },
                  { brname: 'Mali', name: 'Mali',
                    a2: 'ML', a3: 'MLI', number: 466 },
                  { brname: 'Malta', name: 'Malta',
                    a2: 'MT', a3: 'MLT', number: 470 },
                  { brname: 'Malásia', name: 'Malaysia',
                    a2: 'MY', a3: 'MYS', number: 458 },
                  { brname: 'Marianas Setentrionais', name: 'Northern Mariana Islands',
                    a2: 'MP', a3: 'MNP', number: 580 },
                  { brname: 'Marrocos', name: 'Morocco',
                    a2: 'MA', a3: 'MAR', number: 504 },
                  { brname: 'Martinica', name: 'Martinique',
                    a2: 'MQ', a3: 'MTQ', number: 474 },
                  { brname: 'Mauritânia', name: 'Mauritania',
                    a2: 'MR', a3: 'MRT', number: 478 },
                  { brname: 'Maurícia', name: 'Mauritius',
                    a2: 'MU', a3: 'MUS', number: 480 },
                  { brname: 'Mayotte', name: 'Mayotte',
                    a2: 'YT', a3: 'MYT', number: 175 },
                  { brname: 'Moldávia', name: 'Moldova - Republic of',
                    a2: 'MD', a3: 'MDA', number: 498 },
                  { brname: 'Mongólia', name: 'Mongolia',
                    a2: 'MN', a3: 'MNG', number: 496 },
                  { brname: 'Montserrat', name: 'Montserrat',
                    a2: 'MS', a3: 'MSR', number: 500 },
                  { brname: 'Moçambique', name: 'Mozambique',
                    a2: 'MZ', a3: 'MOZ', number: 508 },
                  { brname: 'Myanmar', name: 'Myanmar',
                    a2: 'MM', a3: 'MMR', number: 104 },
                  { brname: 'México', name: 'Mexico',
                    a2: 'MX', a3: 'MEX', number: 484 },
                  { brname: 'Mónaco', name: 'Monaco',
                    a2: 'MC', a3: 'MCO', number: 492 },
                  { brname: 'Namíbia', name: 'Namibia',
                    a2: 'NA', a3: 'NAM', number: 516 },
                  { brname: 'Nauru', name: 'Nauru',
                    a2: 'NR', a3: 'NRU', number: 520 },
                  { brname: 'Nepal', name: 'Nepal',
                    a2: 'NP', a3: 'NPL', number: 524 },
                  { brname: 'Nicarágua', name: 'Nicaragua',
                    a2: 'NI', a3: 'NIC', number: 558 },
                  { brname: 'Nigéria', name: 'Nigeria',
                    a2: 'NG', a3: 'NGA', number: 566 },
                  { brname: 'Niue', name: 'Niue',
                    a2: 'NU', a3: 'NIU', number: 570 },
                  { brname: 'Noruega', name: 'Norway',
                    a2: 'NO', a3: 'NOR', number: 578 },
                  { brname: 'Nova Caledônia', name: 'New Caledonia',
                    a2: 'NC', a3: 'NCL', number: 540 },
                  { brname: 'Nova Zelândia', name: 'New Zealand',
                    a2: 'NZ', a3: 'NZL', number: 554 },
                  { brname: 'Níger', name: 'Niger',
                    a2: 'NE', a3: 'NER', number: 562 },
                  { brname: 'Omã', name: 'Oman',
                    a2: 'OM', a3: 'OMN', number: 512 },
                  { brname: 'Palau', name: 'Palau',
                    a2: 'PW', a3: 'PLW', number: 585 },
                  { brname: 'Palestina', name: 'Palestinian Territory - Occupied',
                    a2: 'PS', a3: 'PSE', number: 275 },
                  { brname: 'Panamá', name: 'Panama',
                    a2: 'PA', a3: 'PAN', number: 591 },
                  { brname: 'Papua-Nova Guiné', name: 'Papua New Guinea',
                    a2: 'PG', a3: 'PNG', number: 598 },
                  { brname: 'Paquistão', name: 'Pakistan',
                    a2: 'PK', a3: 'PAK', number: 586 },
                  { brname: 'Paraguai', name: 'Paraguay',
                    a2: 'PY', a3: 'PRY', number: 600 },
                  { brname: 'Países Baixos', name: 'Netherlands',
                    a2: 'NL', a3: 'NLD', number: 528 },
                  { brname: 'Peru', name: 'Peru',
                    a2: 'PE', a3: 'PER', number: 604 },
                  { brname: 'Pitcairn', name: 'Pitcairn',
                    a2: 'PN', a3: 'PCN', number: 612 },
                  { brname: 'Polinésia Francesa', name: 'French Polynesia',
                    a2: 'PF', a3: 'PYF', number: 258 },
                  { brname: 'Polónia', name: 'Poland',
                    a2: 'PL', a3: 'POL', number: 616 },
                  { brname: 'Porto Rico', name: 'Puerto Rico',
                    a2: 'PR', a3: 'PRI', number: 630 },
                  { brname: 'Portugal', name: 'Portugal',
                    a2: 'PT', a3: 'PRT', number: 620 },
                  { brname: 'Quirguistão', name: 'Kyrgyzstan',
                    a2: 'KG', a3: 'KGZ', number: 417 },
                  { brname: 'Quênia', name: 'Kenya',
                    a2: 'KE', a3: 'KEN', number: 404 },
                  { brname: 'Reino Unido', name: 'United Kingdom',
                    a2: 'GB', a3: 'GBR', number: 826 },
                  { brname: 'República Centro-Africana', name: 'Central African Republic',
                    a2: 'CF', a3: 'CAF', number: 140 },
                  { brname: 'República Checa', name: 'Czech Republic',
                    a2: 'CZ', a3: 'CZE', number: 203 },
                  { brname: 'República Democrática do Congo', name: 'Congo - Democratic Republic of (was Zaire)',
                    a2: 'CD', a3: 'COD', number: 180 },
                  { brname: 'República Dominicana', name: 'Dominican Republic',
                    a2: 'DO', a3: 'DOM', number: 214 },
                  { brname: 'República do Congo', name: 'Congo - Republic of',
                    a2: 'CG', a3: 'COG', number: 178 },
                  { brname: 'Reunião', name: 'Reunion',
                    a2: 'RE', a3: 'REU', number: 638 },
                  { brname: 'Roménia', name: 'Romania',
                    a2: 'RO', a3: 'ROU', number: 642 },
                  { brname: 'Ruanda', name: 'Rwanda',
                    a2: 'RW', a3: 'RWA', number: 646 },
                  { brname: 'Rússia', name: 'Russian Federation',
                    a2: 'RU', a3: 'RUS', number: 643 },
                  { brname: 'Saara Ocidental', name: 'Western Sahara',
                    a2: 'EH', a3: 'ESH', number: 732 },
                  { brname: 'Saint-Pierre e Miquelon', name: 'Saint Pierre and Miquelon',
                    a2: 'PM', a3: 'SPM', number: 666 },
                  { brname: 'Samoa', name: 'Samoa',
                    a2: 'WS', a3: 'WSM', number: 882 },
                  { brname: 'Samoa Americana', name: 'American Samoa',
                    a2: 'AS', a3: 'ASM', number: 16 },
                  { brname: 'San Marino', name: 'San Marino',
                    a2: 'SM', a3: 'SMR', number: 674 },
                  { brname: 'Santa Helena Ascensão e Tristão da Cunha', name: 'Saint Helena',
                    a2: 'SH', a3: 'SHN', number: 654 },
                  { brname: 'Santa Lúcia', name: 'Saint Lucia',
                    a2: 'LC', a3: 'LCA', number: 662 },
                  { brname: 'Seicheles', name: 'Seychelles',
                    a2: 'SC', a3: 'SYC', number: 690 },
                  { brname: 'Senegal', name: 'Senegal',
                    a2: 'SN', a3: 'SEN', number: 686 },
                  { brname: 'Serra Leoa', name: 'Sierra Leone',
                    a2: 'SL', a3: 'SLE', number: 694 },
                  { brname: 'Singapura', name: 'Singapore',
                    a2: 'SG', a3: 'SGP', number: 702 },
                  { brname: 'Somália', name: 'Somalia',
                    a2: 'SO', a3: 'SOM', number: 706 },
                  { brname: 'Sri Lanka', name: 'Sri Lanka',
                    a2: 'LK', a3: 'LKA', number: 144 },
                  { brname: 'Suazilândia', name: 'Swaziland',
                    a2: 'SZ', a3: 'SWZ', number: 748 },
                  { brname: 'Sudão', name: 'Sudan',
                    a2: 'SD', a3: 'SDN', number: 736 },
                  { brname: 'Suriname', name: 'Suriname',
                    a2: 'SR', a3: 'SUR', number: 740 },
                  { brname: 'Suécia', name: 'Sweden',
                    a2: 'SE', a3: 'SWE', number: 752 },
                  { brname: 'Suíça', name: 'Switzerland',
                    a2: 'CH', a3: 'CHE', number: 756 },
                  { brname: 'Svalbard e Jan Mayen', name: 'Svalbard and Jan Mayen Islands',
                    a2: 'SJ', a3: 'SJM', number: 744 },
                  { brname: 'São Cristóvão e Nevis', name: 'Saint Kitts and Nevis',
                    a2: 'KN', a3: 'KNA', number: 659 },
                  { brname: 'São Tomé e Príncipe', name: 'Sao Tome and Principe',
                    a2: 'ST', a3: 'STP', number: 678 },
                  { brname: 'São Vicente e Granadinas', name: 'Saint Vincent and The Grenadines',
                    a2: 'VC', a3: 'VCT', number: 670 },
                  { brname: 'Síria', name: 'Syrian Arab Republic',
                    a2: 'SY', a3: 'SYR', number: 760 },
                  { brname: 'Tailândia', name: 'Thailand',
                    a2: 'TH', a3: 'THA', number: 764 },
                  { brname: 'Taiwan', name: 'Taiwan',
                    a2: 'TW', a3: 'TWN', number: 158 },
                  { brname: 'Tajiquistão', name: 'Tajikistan',
                    a2: 'TJ', a3: 'TJK', number: 762 },
                  { brname: 'Tanzânia', name: 'Tanzania - United Republic of',
                    a2: 'TZ', a3: 'TZA', number: 834 },
                  { brname: 'Terras Austrais e Antárticas Francesas', name: 'French Southern Territories',
                    a2: 'TF', a3: 'ATF', number: 260 },
                  { brname: 'Território Britânico do Oceano Índico', name: 'British Indian Ocean Territory',
                    a2: 'IO', a3: 'IOT', number: 86 },
                  { brname: 'Timor-Leste', name: 'Timor-Leste',
                    a2: 'TL', a3: 'TLS', number: 626 },
                  { brname: 'Togo', name: 'Togo',
                    a2: 'TG', a3: 'TGO', number: 768 },
                  { brname: 'Tonga', name: 'Tonga',
                    a2: 'TO', a3: 'TON', number: 776 },
                  { brname: 'Toquelau', name: 'Tokelau',
                    a2: 'TK', a3: 'TKL', number: 772 },
                  { brname: 'Trinidad e Tobago', name: 'Trinidad and Tobago',
                    a2: 'TT', a3: 'TTO', number: 780 },
                  { brname: 'Tunísia', name: 'Tunisia',
                    a2: 'TN', a3: 'TUN', number: 788 },
                  { brname: 'Turks e Caicos', name: 'Turks and Caicos Islands',
                    a2: 'TC', a3: 'TCA', number: 796 },
                  { brname: 'Turquemenistão', name: 'Turkmenistan',
                    a2: 'TM', a3: 'TKM', number: 795 },
                  { brname: 'Turquia', name: 'Turkey',
                    a2: 'TR', a3: 'TUR', number: 792 },
                  { brname: 'Tuvalu', name: 'Tuvalu',
                    a2: 'TV', a3: 'TUV', number: 798 },
                  { brname: 'Ucrânia', name: 'Ukraine',
                    a2: 'UA', a3: 'UKR', number: 804 },
                  { brname: 'Uganda', name: 'Uganda',
                    a2: 'UG', a3: 'UGA', number: 800 },
                  { brname: 'Uruguai', name: 'Uruguay',
                    a2: 'UY', a3: 'URY', number: 858 },
                  { brname: 'Uzbequistão', name: 'Uzbekistan',
                    a2: 'UZ', a3: 'UZB', number: 860 },
                  { brname: 'Vanuatu', name: 'Vanuatu',
                    a2: 'VU', a3: 'VUT', number: 548 },
                  { brname: 'Vaticano', name: 'Vatican City State (Holy See)',
                    a2: 'VA', a3: 'VAT', number: 336 },
                  { brname: 'Venezuela', name: 'Venezuela',
                    a2: 'VE', a3: 'VEN', number: 862 },
                  { brname: 'Vietnã', name: 'Viet Nam',
                    a2: 'VN', a3: 'VNM', number: 704 },
                  { brname: 'Wallis e Futuna', name: 'Wallis and Futuna Islands',
                    a2: 'WF', a3: 'WLF', number: 876 },
                  { brname: 'Zâmbia', name: 'Zambia',
                    a2: 'ZM', a3: 'ZMB', number: 894 },
                  { brname: 'África do Sul', name: 'South Africa',
                    a2: 'ZA', a3: 'ZAF', number: 710 },
                  { brname: 'Áustria', name: 'Austria',
                    a2: 'AT', a3: 'AUT', number: 40 },
                  { brname: 'Índia', name: 'India',
                    a2: 'IN', a3: 'IND', number: 356 }
                ])
