State.create!([
                { name: 'Acre', abbreviation: 'AC', country_id: 31 },
                { name: 'Alagoas', abbreviation: 'AL', country_id: 31 },
                { name: 'Amapá', abbreviation: 'AP', country_id: 31 },
                { name: 'Amazonas', abbreviation: 'AM', country_id: 31 },
                { name: 'Bahia', abbreviation: 'BA', country_id: 31 },
                { name: 'Ceará', abbreviation: 'CE', country_id: 31 },
                { name: 'Distrito Federal', abbreviation: 'DF', country_id: 31 },
                { name: 'Espírito Santo', abbreviation: 'ES', country_id: 31 },
                { name: 'Goiás', abbreviation: 'GO', country_id: 31 },
                { name: 'Maranhão', abbreviation: 'MA', country_id: 31 },
                { name: 'Mato Grosso', abbreviation: 'MT', country_id: 31 },
                { name: 'Mato Grosso do Sul', abbreviation: 'MS', country_id: 31 },
                { name: 'Minas Gerais', abbreviation: 'MG', country_id: 31 },
                { name: 'Paraná', abbreviation: 'PR', country_id: 31 },
                { name: 'Paraíba', abbreviation: 'PB', country_id: 31 },
                { name: 'Pará', abbreviation: 'PA', country_id: 31 },
                { name: 'Pernambuco', abbreviation: 'PE', country_id: 31 },
                { name: 'Piauí', abbreviation: 'PI', country_id: 31 },
                { name: 'Rio Grande do Norte', abbreviation: 'RN', country_id: 31 },
                { name: 'Rio Grande do Sul', abbreviation: 'RS', country_id: 31 },
                { name: 'Rio de Janeiro', abbreviation: 'RJ', country_id: 31 },
                { name: 'Rondônia', abbreviation: 'RO', country_id: 31 },
                { name: 'Roraima', abbreviation: 'RR', country_id: 31 },
                { name: 'Santa Catarina', abbreviation: 'SC', country_id: 31 },
                { name: 'Sergipe', abbreviation: 'SE', country_id: 31 },
                { name: 'São Paulo', abbreviation: 'SP', country_id: 31 },
                { name: 'Tocantins', abbreviation: 'TO', country_id: 31 }
              ])
