Stateregion.create!([
                      { name: 'Agreste Alagoano', state_id: 2 },
                      { name: 'Agreste Paraibano', state_id: 15 },
                      { name: 'Agreste Pernambucano', state_id: 17 },
                      { name: 'Agreste Potiguar', state_id: 20 },
                      { name: 'Agreste Sergipano', state_id: 26 },
                      { name: 'Araçatuba', state_id: 25 },
                      { name: 'Araraquara', state_id: 25 },
                      { name: 'Assis', state_id: 25 },
                      { name: 'Baixadas', state_id: 19 },
                      { name: 'Baixo Amazonas', state_id: 14 },
                      { name: 'Bauru', state_id: 25 },
                      { name: 'Borborema', state_id: 15 },
                      { name: 'Campinas', state_id: 25 },
                      { name: 'Campo das Vertentes', state_id: 13 },
                      { name: 'Central Espírito-santense', state_id: 8 },
                      { name: 'Central Mineira', state_id: 13 },
                      { name: 'Central Potiguar', state_id: 20 },
                      { name: 'Centro Amazonense', state_id: 4 },
                      { name: 'Centro Fluminense', state_id: 19 },
                      { name: 'Centro Goiano', state_id: 9 },
                      { name: 'Centro Maranhense', state_id: 10 },
                      { name: 'Centro Norte Baiano', state_id: 5 },
                      { name: 'Centro Norte de Mato Grosso do Sul', state_id: 12 },
                      { name: 'Centro-Norte Piauiense', state_id: 18 },
                      { name: 'Centro Ocidental Paranaense', state_id: 16 },
                      { name: 'Centro Ocidental Rio-grandense', state_id: 21 },
                      { name: 'Centro Oriental Paranaense', state_id: 16 },
                      { name: 'Centro Oriental Rio-grandense', state_id: 21 },
                      { name: 'Centro Sul Baiano', state_id: 5 },
                      { name: 'Centro-Sul Cearense', state_id: 6 },
                      { name: 'Centro-Sul Mato-grossense', state_id: 11 },
                      { name: 'Centro-Sul Paranaense', state_id: 16 },
                      { name: 'Distrito Federal', state_id: 7 },
                      { name: 'Extremo Oeste Baiano', state_id: 5 },
                      { name: 'Grande Florianópolis', state_id: 24 },
                      { name: 'Itapetininga', state_id: 25 },
                      { name: 'Jaguaribe', state_id: 6 },
                      { name: 'Jequitinhonha', state_id: 13 },
                      { name: 'Leste Alagoano', state_id: 2 },
                      { name: 'Leste de Mato Grosso do Sul', state_id: 12 },
                      { name: 'Leste Goiano', state_id: 9 },
                      { name: 'Leste Maranhense', state_id: 10 },
                      { name: 'Leste Potiguar', state_id: 20 },
                      { name: 'Leste Rondoniense', state_id: 22 },
                      { name: 'Leste Sergipano', state_id: 26 },
                      { name: 'Litoral Norte Espírito-santense', state_id: 8 },
                      { name: 'Litoral Sul Paulista', state_id: 25 },
                      { name: 'Macro Metropolitana Paulista', state_id: 25 },
                      { name: 'Madeira-Guaporé', state_id: 22 },
                      { name: 'Marajó', state_id: 14 },
                      { name: 'Marília', state_id: 25 },
                      { name: 'Mata Paraibana', state_id: 15 },
                      { name: 'Mata Pernambucana', state_id: 17 },
                      { name: 'Metropolitana de Belém', state_id: 14 },
                      { name: 'Metropolitana de Belo Horizonte', state_id: 13 },
                      { name: 'Metropolitana de Curitiba', state_id: 16 },
                      { name: 'Metropolitana de Fortaleza', state_id: 6 },
                      { name: 'Metropolitana de Porto Alegre', state_id: 21 },
                      { name: 'Metropolitana de Recife', state_id: 17 },
                      { name: 'Metropolitana de Salvador', state_id: 5 },
                      { name: 'Metropolitana de São Paulo', state_id: 25 },
                      { name: 'Metropolitana do Rio de Janeiro', state_id: 19 },
                      { name: 'Nordeste Baiano', state_id: 5 },
                      { name: 'Nordeste Mato-grossense', state_id: 11 },
                      { name: 'Nordeste Paraense', state_id: 14 },
                      { name: 'Nordeste Rio-grandense', state_id: 21 },
                      { name: 'Noroeste Cearense', state_id: 6 },
                      { name: 'Noroeste de Minas', state_id: 13 },
                      { name: 'Noroeste Espírito-santense', state_id: 8 },
                      { name: 'Noroeste Fluminense', state_id: 19 },
                      { name: 'Noroeste Goiano', state_id: 9 },
                      { name: 'Noroeste Paranaense', state_id: 16 },
                      { name: 'Noroeste Rio-grandense', state_id: 21 },
                      { name: 'Norte Amazonense', state_id: 4 },
                      { name: 'Norte Catarinense', state_id: 24 },
                      { name: 'Norte Cearense', state_id: 6 },
                      { name: 'Norte Central Paranaense', state_id: 16 },
                      { name: 'Norte de Minas', state_id: 13 },
                      { name: 'Norte de Roraima', state_id: 23 },
                      { name: 'Norte do Amapá', state_id: 3 },
                      { name: 'Norte Fluminense', state_id: 19 },
                      { name: 'Norte Goiano', state_id: 9 },
                      { name: 'Norte Maranhense', state_id: 10 },
                      { name: 'Norte Mato-grossense', state_id: 11 },
                      { name: 'Norte Piauiense', state_id: 18 },
                      { name: 'Norte Pioneiro Paranaense', state_id: 16 },
                      { name: 'Ocidental do Tocantins', state_id: 27 },
                      { name: 'Oeste Catarinense', state_id: 24 },
                      { name: 'Oeste de Minas', state_id: 13 },
                      { name: 'Oeste Maranhense', state_id: 10 },
                      { name: 'Oeste Paranaense', state_id: 16 },
                      { name: 'Oeste Potiguar', state_id: 20 },
                      { name: 'Oriental do Tocantins', state_id: 27 },
                      { name: 'Pantanais Sul Mato-grossense', state_id: 12 },
                      { name: 'Piracicaba', state_id: 25 },
                      { name: 'Presidente Prudente', state_id: 25 },
                      { name: 'Ribeirão Preto', state_id: 25 },
                      { name: 'São Francisco Pernambucano', state_id: 17 },
                      { name: 'São José do Rio Preto', state_id: 25 },
                      { name: 'Serrana', state_id: 24 },
                      { name: 'Sertão Alagoano', state_id: 2 },
                      { name: 'Sertão Paraibano', state_id: 15 },
                      { name: 'Sertão Pernambucano', state_id: 17 },
                      { name: 'Sertão Sergipano', state_id: 26 },
                      { name: 'Sertões Cearenses', state_id: 6 },
                      { name: 'Sudeste Mato-grossense', state_id: 11 },
                      { name: 'Sudeste Paraense', state_id: 14 },
                      { name: 'Sudeste Paranaense', state_id: 16 },
                      { name: 'Sudeste Piauiense', state_id: 18 },
                      { name: 'Sudeste Rio-grandense', state_id: 21 },
                      { name: 'Sudoeste Amazonense', state_id: 4 },
                      { name: 'Sudoeste de Mato Grosso do Sul', state_id: 12 },
                      { name: 'Sudoeste Mato-grossense', state_id: 11 },
                      { name: 'Sudoeste Paraense', state_id: 14 },
                      { name: 'Sudoeste Paranaense', state_id: 16 },
                      { name: 'Sudoeste Piauiense', state_id: 18 },
                      { name: 'Sudoeste Rio-grandense', state_id: 21 },
                      { name: 'Sul Amazonense', state_id: 4 },
                      { name: 'Sul Baiano', state_id: 5 },
                      { name: 'Sul Catarinense', state_id: 24 },
                      { name: 'Sul Cearense', state_id: 6 },
                      { name: 'Sul de Roraima', state_id: 23 },
                      { name: 'Sul do Amapá', state_id: 3 },
                      { name: 'Sul Espírito-santense', state_id: 8 },
                      { name: 'Sul Fluminense', state_id: 19 },
                      { name: 'Sul Goiano', state_id: 9 },
                      { name: 'Sul Maranhense', state_id: 10 },
                      { name: 'Sul/Sudoeste de Minas', state_id: 13 },
                      { name: 'Triângulo Mineiro/Alto Paranaíba', state_id: 13 },
                      { name: 'Vale do Acre', state_id: 1 },
                      { name: 'Vale do Itajaí', state_id: 24 },
                      { name: 'Vale do Juruá', state_id: 1 },
                      { name: 'Vale do Mucuri', state_id: 13 },
                      { name: 'Vale do Paraíba Paulista', state_id: 25 },
                      { name: 'Vale do Rio Doce', state_id: 13 },
                      { name: 'Vale São-Franciscano da Bahia', state_id: 5 },
                      { name: 'Zona da Mata', state_id: 13 }
                    ])
