development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_NAME'] %>_development
  username: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_USER'] %>
  password: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_NAME'] %>_test
  username: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_USER'] %>
  password: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_NAME'] %>_production
  username: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_USER'] %>
  password: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_PASSWORD'] %>
