development:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_HOST']%>
  database: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_PREFIX']%>development
  username: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_USER']%>
  password: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_PASSWORD']%>

test:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_HOST']%>
  database: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_PREFIX']%>test
  username: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_USER'] %>
  password: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_HOST']%>
  database: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_PREFIX']%>production
  username: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_USER'] %>
  password: <%= ENV['GRADUATE_CERTIFICATE_DATABASE_PASSWORD'] %>
