development:
  secret_key_base: <%= ENV['GRADUATE_CERTIFICATE_KEY_BASE']%>

test:
  secret_key_base: <%= ENV['GRADUATE_CERTIFICATE_KEY_BASE']%>

production:
  secret_key_base: <%= ENV['GRADUATE_CERTIFICATE_KEY_BASE']%>
