require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InstitutiontypesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Institutiontype. As you add validations to Institutiontype, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InstitutiontypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all institutiontypes as @institutiontypes" do
      institutiontype = Institutiontype.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:institutiontypes)).to eq([institutiontype])
    end
  end

  describe "GET show" do
    it "assigns the requested institutiontype as @institutiontype" do
      institutiontype = Institutiontype.create! valid_attributes
      get :show, {:id => institutiontype.to_param}, valid_session
      expect(assigns(:institutiontype)).to eq(institutiontype)
    end
  end

  describe "GET new" do
    it "assigns a new institutiontype as @institutiontype" do
      get :new, {}, valid_session
      expect(assigns(:institutiontype)).to be_a_new(Institutiontype)
    end
  end

  describe "GET edit" do
    it "assigns the requested institutiontype as @institutiontype" do
      institutiontype = Institutiontype.create! valid_attributes
      get :edit, {:id => institutiontype.to_param}, valid_session
      expect(assigns(:institutiontype)).to eq(institutiontype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Institutiontype" do
        expect {
          post :create, {:institutiontype => valid_attributes}, valid_session
        }.to change(Institutiontype, :count).by(1)
      end

      it "assigns a newly created institutiontype as @institutiontype" do
        post :create, {:institutiontype => valid_attributes}, valid_session
        expect(assigns(:institutiontype)).to be_a(Institutiontype)
        expect(assigns(:institutiontype)).to be_persisted
      end

      it "redirects to the created institutiontype" do
        post :create, {:institutiontype => valid_attributes}, valid_session
        expect(response).to redirect_to(Institutiontype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved institutiontype as @institutiontype" do
        post :create, {:institutiontype => invalid_attributes}, valid_session
        expect(assigns(:institutiontype)).to be_a_new(Institutiontype)
      end

      it "re-renders the 'new' template" do
        post :create, {:institutiontype => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested institutiontype" do
        institutiontype = Institutiontype.create! valid_attributes
        put :update, {:id => institutiontype.to_param, :institutiontype => new_attributes}, valid_session
        institutiontype.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested institutiontype as @institutiontype" do
        institutiontype = Institutiontype.create! valid_attributes
        put :update, {:id => institutiontype.to_param, :institutiontype => valid_attributes}, valid_session
        expect(assigns(:institutiontype)).to eq(institutiontype)
      end

      it "redirects to the institutiontype" do
        institutiontype = Institutiontype.create! valid_attributes
        put :update, {:id => institutiontype.to_param, :institutiontype => valid_attributes}, valid_session
        expect(response).to redirect_to(institutiontype)
      end
    end

    describe "with invalid params" do
      it "assigns the institutiontype as @institutiontype" do
        institutiontype = Institutiontype.create! valid_attributes
        put :update, {:id => institutiontype.to_param, :institutiontype => invalid_attributes}, valid_session
        expect(assigns(:institutiontype)).to eq(institutiontype)
      end

      it "re-renders the 'edit' template" do
        institutiontype = Institutiontype.create! valid_attributes
        put :update, {:id => institutiontype.to_param, :institutiontype => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested institutiontype" do
      institutiontype = Institutiontype.create! valid_attributes
      expect {
        delete :destroy, {:id => institutiontype.to_param}, valid_session
      }.to change(Institutiontype, :count).by(-1)
    end

    it "redirects to the institutiontypes list" do
      institutiontype = Institutiontype.create! valid_attributes
      delete :destroy, {:id => institutiontype.to_param}, valid_session
      expect(response).to redirect_to(institutiontypes_url)
    end
  end

end
