require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StreetnamesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Streetname. As you add validations to Streetname, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StreetnamesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all streetnames as @streetnames" do
      streetname = Streetname.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:streetnames)).to eq([streetname])
    end
  end

  describe "GET show" do
    it "assigns the requested streetname as @streetname" do
      streetname = Streetname.create! valid_attributes
      get :show, {:id => streetname.to_param}, valid_session
      expect(assigns(:streetname)).to eq(streetname)
    end
  end

  describe "GET new" do
    it "assigns a new streetname as @streetname" do
      get :new, {}, valid_session
      expect(assigns(:streetname)).to be_a_new(Streetname)
    end
  end

  describe "GET edit" do
    it "assigns the requested streetname as @streetname" do
      streetname = Streetname.create! valid_attributes
      get :edit, {:id => streetname.to_param}, valid_session
      expect(assigns(:streetname)).to eq(streetname)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Streetname" do
        expect {
          post :create, {:streetname => valid_attributes}, valid_session
        }.to change(Streetname, :count).by(1)
      end

      it "assigns a newly created streetname as @streetname" do
        post :create, {:streetname => valid_attributes}, valid_session
        expect(assigns(:streetname)).to be_a(Streetname)
        expect(assigns(:streetname)).to be_persisted
      end

      it "redirects to the created streetname" do
        post :create, {:streetname => valid_attributes}, valid_session
        expect(response).to redirect_to(Streetname.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved streetname as @streetname" do
        post :create, {:streetname => invalid_attributes}, valid_session
        expect(assigns(:streetname)).to be_a_new(Streetname)
      end

      it "re-renders the 'new' template" do
        post :create, {:streetname => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested streetname" do
        streetname = Streetname.create! valid_attributes
        put :update, {:id => streetname.to_param, :streetname => new_attributes}, valid_session
        streetname.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested streetname as @streetname" do
        streetname = Streetname.create! valid_attributes
        put :update, {:id => streetname.to_param, :streetname => valid_attributes}, valid_session
        expect(assigns(:streetname)).to eq(streetname)
      end

      it "redirects to the streetname" do
        streetname = Streetname.create! valid_attributes
        put :update, {:id => streetname.to_param, :streetname => valid_attributes}, valid_session
        expect(response).to redirect_to(streetname)
      end
    end

    describe "with invalid params" do
      it "assigns the streetname as @streetname" do
        streetname = Streetname.create! valid_attributes
        put :update, {:id => streetname.to_param, :streetname => invalid_attributes}, valid_session
        expect(assigns(:streetname)).to eq(streetname)
      end

      it "re-renders the 'edit' template" do
        streetname = Streetname.create! valid_attributes
        put :update, {:id => streetname.to_param, :streetname => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested streetname" do
      streetname = Streetname.create! valid_attributes
      expect {
        delete :destroy, {:id => streetname.to_param}, valid_session
      }.to change(Streetname, :count).by(-1)
    end

    it "redirects to the streetnames list" do
      streetname = Streetname.create! valid_attributes
      delete :destroy, {:id => streetname.to_param}, valid_session
      expect(response).to redirect_to(streetnames_url)
    end
  end

end
